{
 "title": "SSM Patching Status",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overall Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Patching Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Account Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "account.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Environment Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "environment.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Region Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "region.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PatchGroup Servers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "patchGroup.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Customer Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "customer.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SSM Failed Patching Instances",
   "type": "table",
   "description": "SSM Failed Patching Instances",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "status:Failed",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Success vs Failed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Account Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "account.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Customer Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "customer.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Environment Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "environment.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Patching Group Status - Success",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "patchGroup.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "status:Success",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Patching Group Status - Failed",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "patchGroup.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "status:Failed",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Region Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "region.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "status.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "SSM Patching Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "SSM Patching Log",
   "type": "table",
   "description": "SSM Patching Log",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}